CREATE TABLE BOOKS
(ISBN varchar2(20) PRIMARY KEY  ,
CONTENT varchar2(500) NOT NULL , 
NAME varchar2(60) NOT NULL  , 
SELF_NUMBER varchar2(4) NOT NULL ,
SECTION_NAME varchar(15) NOT NULL , LIBRARIAN_ID NUMBER(6),
CONSTRAINT LIBRARIAN_ID_FKBOOK FOREIGN KEY (LIBRARIAN_ID)
REFERENCES LIBRARIANS (LIBRARIAN_ID) );


CREATE TABLE LIBRARIANS
(LIBRARIAN_ID NUMBER(6)  ,
NAME VARCHAR2(10) NOT NULL ,
SALARY NUMERIC(7,2) NOT NULL ,
SHIFT VARCHAR2(40) NOT NULL ,
PHONE_NUMBER VARCHAR2(12),
CONSTRAINT LIBRARIAN_ID_PK PRIMARY KEY (LIBRARIAN_ID) );

CREATE TABLE WRITE
(ORCID VARCHAR(20) ,
ISBN varchar2(20),
PRIMARY KEY (ORCID , ISBN),
CONSTRAINT ORCID_FKWRITE FOREIGN KEY (ORCID)
REFERENCES WRITERS (ORCID) ,
CONSTRAINT ISBN_FKWRITE FOREIGN KEY (ISBN)
REFERENCES BOOKS (ISBN) );


CREATE TABLE WRITERS
(ORCID VARCHAR(20) PRIMARY KEY,
NAME VARCHAR(15) NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
TYPE VARCHAR(15) NOT NULL,
PHONE_NUMBER VARCHAR(12));


CREATE TABLE PUBLISHING_HOUSES
(PUBLISHER_ID NUMBER(7) ,
EMAIL VARCHAR2(70) NOT NULL,
NAME VARCHAR2(40) NOT NULL,
PHONE_NUMBER VARCHAR2(12),
CONSTRAINT PUBLISHER_ID_PK PRIMARY KEY (PUBLISHER_ID),
CONSTRAINT EMAIL_UQ UNIQUE (EMAIL) );

CREATE TABLE PUBLISH 
( PUBLISHER_ID NUMBER(7),
ISBN VARCHAR2(20),
PRIMARY KEY( PUBLISHER_ID  , ISBN ),
CONSTRAINT PUBLISHER_ID_FKPUBLISH FOREIGN KEY(PUBLISHER_ID) REFERENCES PUBLISHING_HOUSES (PUBLISHER_ID),
CONSTRAINT ISBN_FKPUBLISH FOREIGN KEY(ISBN) REFERENCES BOOKS(ISBN) );

CREATE TABLE USERS
( USER_ID NUMBER(15) , 
EMAIL_ADDRESS VARCHAR2(50) NOT NULL ,
 NAME VARCHAR2(30) NOT NULL , 
PHONE_NUMBER VARCHAR2(12) ,
CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID) );

CREATE TABLE READ ( 
USER_ID NUMBER(15) ,
ISBN VARCHAR2(20),
PRIMARY KEY (USER_ID , ISBN ) ,
CONSTRAINT USER_ID_FKREAD FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ,
CONSTRAINT ISBN_FKREAD FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN) );

CREATE TABLE PCS ( 
IP_ADDRESS VARCHAR2(15) PRIMARY KEY , 
PASSWORD VARCHAR2(15) NOT NULL , 
LIBRARIAN_ID NUMBER(6),
USER_ID NUMBER(15),
CONSTRAINT LIBRARIAN_ID_FKPCS FOREIGN KEY (LIBRARIAN_ID)
REFERENCES LIBRARIANS (LIBRARIAN_ID) ,
CONSTRAINT USER_ID_FKPCS FOREIGN KEY (USER_ID)
REFERENCES USERS (USER_ID) );


CREATE TABLE ACCESS_PCS
(USER_ID NUMBER(15) PRIMARY KEY ,
IP_ADDRESS VARCHAR2(15) ,
CONSTRAINT USER_ID_FKACCES FOREIGN KEY (USER_ID) 
REFERENCES USERS (USER_ID) ,
CONSTRAINT IP_ADDRESS_FKACCES FOREIGN KEY (IP_ADDRESS) 
REFERENCES  PCS (IP_ADDRESS) );


CREATE TABLE LECTURERS (
LECTURER_ID NUMBER (15),
CONSTRAINT USER_ID_FK FOREIGN KEY (LECTURER_ID) REFERENCES USERS (USER_ID),
CONSTRAINT LECTURER_ID_PK PRIMARY KEY (LECTURER_ID) );


CREATE TABLE STUDENTS ( STUDENT_ID NUMBER(10) , DEGREE VARCHAR2(15) NOT NULL ,
CONSTRAINT USER_ID_FKSTU FOREIGN KEY ( STUDENT_ID ) REFERENCES USERS (USER_ID),
CONSTRAINT STUDENT_PK PRIMARY KEY(STUDENT_ID ) );

CREATE TABLE BORROW 
( LECTURER_ID NUMBER (15),
ISBN varchar2(20),
PRIMARY KEY (LECTURER_ID , ISBN),
CONSTRAINT LECTURER_ID_FKBORROW FOREIGN KEY (LECTURER_ID) REFERENCES LECTURERS (LECTURER_ID), 
CONSTRAINT ISBN_FKBORROW FOREIGN KEY (ISBN) REFERENCES BOOKS (ISBN));



CREATE TABLE LEC_COURSE (
LECTURER_ID NUMBER (15) ,
COURSES VARCHAR2(30) ,
CONSTRAINT LEC_ID_FK FOREIGN KEY (LECTURER_ID) 
REFERENCES LECTURERS (LECTURER_ID) ,
PRIMARY KEY(LECTURER_ID ,COURSES )
 );
